apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ncareer
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_0900_ai_ci"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "ncareer7897!"
            - name: MYSQL_DATABASE
              value: "ncareer"
            - name: MYSQL_USER
              value: "ncareer"
            - name: MYSQL_PASSWORD
              value: "ncareer7897!"
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command: ["mysqladmin","ping","-h","127.0.0.1","-uroot","-p$(MYSQL_ROOT_PASSWORD)"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["mysqladmin","ping","-h","127.0.0.1","-uroot","-p$(MYSQL_ROOT_PASSWORD)"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path   # k3s 기본 StorageClass
        resources:
          requests:
            storage: 20Gi
