apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          args: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_0900_ai_ci"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ilhaeng7897!
            - name: MYSQL_DATABASE
              value: ilhaeng
            - name: MYSQL_USER
              value: ilhaeng
            - name: MYSQL_PASSWORD
              value: ilhaeng7897!
          ports:
            - containerPort: 3306