# crawler-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: crawler-config
data:
  # Presigned URL 발급 API
  PRESIGN_API: "http://ilhaeng-staging-service:80"

  # 크롤러 공통 ENV (각 스크립트가 읽어감)
  OUTDIR: "/data/out"
  NCP_DEFAULT_DIR: "stage"      # 업로드 루트 prefix
  PAGES: "1"
  DETAIL_DELAY: "0.3"
  WORKERS: "6"
  TZ: "Asia/Seoul"

  # run_all.py 실행 파라미터(쉘에서 env 확장해 args로 전달)
  CONCURRENCY: "3"
  TIMEOUT: "2400"              # 초
  RETRIES: "1"

  REDIS_URL: "redis://redis-service:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: crawler-secret
type: Opaque
stringData:
  presign-auth: "Bearer XXXXXX"