apiVersion: v1
kind: Secret
metadata:
  name: my-git-repo                                   # Secret 이름 (ArgoCD에서 구분용)
  namespace: argocd                                   # ArgoCD가 설치된 Namespace (보통 argocd)
  labels:
    argocd.argoproj.io/secret-type: repository        # 중요: 이 label 이 있어야 ArgoCD가 Repository 용도의 Secret으로 인식함
stringData:                                           # 평문 데이터 (적용 시 자동 base64 인코딩 됨)
  type: git                                           # repository 타입 (git, helm 등 지정 가능)
  url: https://github.com/X-Kusitms-1/MANIFEST.git      # GitHub Repository URL
  username: SeongHo5356                                   # GitHub 사용자 이름
  password: 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                                # GitHub Personal Access Token (https 인증용)
