apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    chart: opensearch
    targetRevision: 2.21.0          # chart 버전 (원하는 버전)
    helm:
      valueFiles:
        - staging/opensearch/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
