apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: opensearch
spec:
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: metrics
      port: 9600
      targetPort: 9600
  type: ClusterIP
