clusterName: opensearch-staging
replicas: 1

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "ilhaeng7897!"

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

persistence:
  enabled: false

service:
  type: ClusterIP
  port: 9200

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: opensearch.staging.ilhaeng.cloud
      paths:
        - path: /
          pathType: Prefix